### ISSUE TITLE
Lock Question in /src/thread/GetAllTopics

### ISSUE THREAD

**Issue by fineweekDay** [MingZheng27/JavaSpider#1]
The code is as follows:
	<font color="#008000"><b>`public void run() {`
		&emsp;`Lock lock = new ReentrantLock();`
		&emsp;`try{`
			&emsp;&emsp;`lock.lock();`
			&emsp;&emsp;`GetTopicId.getChildTopics(main_topic_id, conn);`
		&emsp;`}catch(Exception e){`
			&emsp;&emsp;`e.printStackTrace();`
		&emsp;`}finally{`
			&emsp;&emsp;`lock.unlock();`
		&emsp;`}`
	`}`</b></font>
My question is the lock in run method is the owner of the thread(every thread has its own lock?),then the use is what? expect for u answer,thx.

**Comment by MingZheng27** [comment]
I'm sorry,I write this project when i'm new in java so I write this in a wrong way,the lock should be defined out of run method,I will fix this bug this weekend as I only have time this weekend,thanks a lot for giving me this warn.

**Comment by fineweekDay** [comment]
@MingZheng27  well,thx for u reply.As for me,the lock defined outside the run method would cause a question of low concurrency.If the main just getAllChildtopic ,the lock may should be ignored,well,i test it smoothly(The lock mybe useless at all here). Then,thx  again for the code as it helps me a lot.
